apiVersion: v1
kind: Service
metadata:
  name: {NAME}-sglang
  namespace: inference-system
  labels:
    app: {NAME}-sglang
spec:
  ports:
    - name: server 
      port: 30000
      targetPort: 30000
      protocol: TCP
  clusterIP: None
  selector:
    app: {NAME}-sglang
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {NAME}-sglang
  namespace: inference-system
spec:
  selector:
    matchLabels:
      app: {NAME}-sglang # has to match .spec.template.metadata.labels
  replicas: {REPLICA} # by default is 1
  serviceName: {NAME}-sglang
  template:
    metadata:
      labels:
        app: {NAME}-sglang # has to match .spec.selector.matchLabels
        server: {NAME}
    spec:
      terminationGracePeriodSeconds: 10
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
          - cluster.local
          - svc.cluster.local
          - inference-system.svc.cluster.local
          - {NAME}-sglang.inference-system.svc.cluster.local
        options:
          - name: ndots
            value: "5"
      containers:
      - name: {NAME}
        command:
        - "sleep"
        args:
        - "infinity"
        image: {IMAGE}
        imagePullPolicy: Always
        resources:
          requests:
            nvidia.com/gpu: "8"
            rdma/hca_shared_devices: "1"
          limits:
            nvidia.com/gpu: "8"
            rdma/hca_shared_devices: "1"
        ports:
        - containerPort: 30000
          name: server
        volumeMounts:
        - name: result-path
          mountPath: /data/benchmark/results
        - name: model-path
          mountPath: /models
        - name: shm-volume
          mountPath: /dev/shm
        securityContext:
          privileged: true
          #capabilities:
          #  add: [ "IPC_LOCK" ]
        env:
        - name: NCCL_SOCKET_IFNAME
          value: "eth0"
        # - name: NCCL_DEBUG
        #   value: "INFO"
        - name: TP
          value: "{TP}"
        - name: DP
          value: "{DP}"
        - name: ENABLE_DEEPEP
          value: "0"
        - name: WORLD_SIZE
          value: "{REPLICA}"
        - name: GLOO_SOCKET_IFNAME
          value: "eth0"
        - name: COMPILE_OPTS
          value: "--disable-cuda-graph --log-level debug"
        - name: MEM_FRACTION_STATIC
          value: "0.8"
        - name: SERVER_NAME
          value: "{NAME}"
        - name: NCCL_IB_HCA
          value: "mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_8:1"
        - name: KV_TRANSFER_DEVICE
          value: "mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_8"
        - name: SGLANG_SET_CPU_AFFINITY
          value: "1"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # - name: ETCD_ADDR
        #   value: "10.133.0.25:30299"
      volumes:
        - name: result-path
          hostPath:
            path: /data/benchmark/results
        - name: model-path
          hostPath:
            path: /data/models/deepseek-r1
        - name: shm-volume
          emptyDir:
            medium: Memory