name: Manual Workflow for main code benchmark
run-name: "Deploy main code to staging env to benchmark"
on:
  workflow_dispatch:  # 只允许手动触发
    inputs:
      concurrency:
        required: false
        default: "16"
        description: "最大并发数设置"
        type: string

concurrency:
  group: "merge-pr-workflow"
  cancel-in-progress: false
jobs:
  deploy:
    name: "Deploy to staging env to test"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$STAGING_SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $STAGING_SSH_HOST
            User $STAGING_SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port $STAGING_SSH_PORT
          END
        env:
          STAGING_SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          STAGING_SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          STAGING_SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}

      - name: Start the benchmark
        run: |
          ssh staging "bash -c 'export MAX_CONCURRENCIES=${{ github.event.inputs.concurrency }}; cd /root/sglang-auto/benchmark/furion-cn && bash auto_benchmark.sh ${{ github.head_ref || github.ref_name }}'"
        env:
          MAX_CONCURRENCIES: ${{ github.event.inputs.concurrency }}

      - name: Clean up
        run: |
          ssh staging "bash -c 'cd /root/sglang-auto/benchmark/furion-cn && ./clean_up.sh'"
