name: Manual Workflow for main code benchmark
run-name: "Deploy main code to staging env to benchmark"
on:
  workflow_dispatch:  # 只允许手动触发
    inputs:
      prefill_replica:
        description: '预填充副本数'
        required: false
        default: '2'
        type: string
      prefill_tp:
        description: '预填充 TP 值'
        required: false
        default: '16'
        type: string
      prefill_dp:
        description: '预填充 DP 值'
        required: false
        default: '4'
        type: string
      decode_replica:
        description: '解码副本数'
        required: false
        default: '2'
        type: string
      decode_tp:
        description: '解码 TP 值'
        required: false
        default: '16'
        type: string
      decode_dp:
        description: '解码 DP 值'
        required: false
        default: '16'
        type: string
      max_concurrencies:
        description: '最大并发数（逗号分隔的多个值）'
        required: false
        default: '1024'
        type: string
      

concurrency:
  group: "merge-pr-workflow"
  cancel-in-progress: false
jobs:
  deploy:
    name: "Deploy to staging env to test"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$STAGING_SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $STAGING_SSH_HOST
            User $STAGING_SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port $STAGING_SSH_PORT
          END
        env:
          STAGING_SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          STAGING_SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          STAGING_SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}

      - name: Start the benchmark
        run: |
          ssh staging "bash -c 'cd /root/sglang-auto/benchmark/furion-cn && \
          python3 auto_benchmark.py run \
          --prefill-replica ${{ github.event.inputs.prefill_replica }} \
          --prefill-tp ${{ github.event.inputs.prefill_tp }} \
          --prefill-dp ${{ github.event.inputs.prefill_dp }} \
          --decode-replica ${{ github.event.inputs.decode_replica }} \
          --decode-tp ${{ github.event.inputs.decode_tp }} \
          --decode-dp ${{ github.event.inputs.decode_dp }} \
          --max-concurrencies ${{ github.event.inputs.max_concurrencies }}'"

      - name: Clean up
        run: |
          ssh staging "bash -c 'cd /root/sglang-auto/benchmark/furion-cn && ./clean_up.sh'"
