name: Merge Test CI
run-name: "Merge PR to staging env to test"
on:
  pull_request_target:
    types:
      # - closed # 关闭PR时触发, 合并pr时取消注释
      - opened
      - synchronize
      - reopened
concurrency:
  group: "merge-pr-workflow"
  cancel-in-progress: false
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging env to test"
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true 合并PR时，取消注释
    if: true
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$STAGING_SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $STAGING_SSH_HOST
            User $STAGING_SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port $STAGING_SSH_PORT
          END
        env:
          STAGING_SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          STAGING_SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          STAGING_SSH_PORT: ${{ secrets.STAGING_SSH_PORT }}
          MAX_CONCURRENCIES: 16 # 最大并发数

      - name: Start the benchmark
        run: |
          ssh staging "bash -c 'export MAX_CONCURRENCIES=${MAX_CONCURRENCIES}; cd /root/sglang-auto/benchmark/furion-cn && ./auto_benchmark.sh'"
        env:
          MAX_CONCURRENCIES: 16
